### ISSUE TITLE
NullPointerException on Click first ActionBarMenuItem after Rotation

### ISSUE THREAD

**Issue by slumdroid** [SunyataZero/KindMind#4]
KindMind crashes on Click the first ActionBarMenuItem ("ic_action_accept") after change the orientation device.

The StackTrace: 

E/AndroidRuntime( 5940): java.lang.NullPointerException
E/AndroidRuntime( 5940): 	at android.content.ComponentName.<init>(ComponentName.java:75)
E/AndroidRuntime( 5940): 	at android.content.Intent.<init>(Intent.java:3301)
E/AndroidRuntime( 5940): 	at com.sunyata.kindmind.List.ListFragmentC.sortDataWithService(ListFragmentC.java:204)
E/AndroidRuntime( 5940): 	at com.sunyata.kindmind.Main.MainActivityC.fireClearDatabaseAndUpdateGuiEvent(MainActivityC.java:234)
E/AndroidRuntime( 5940): 	at com.sunyata.kindmind.Main.MainActivityC.fireSavePatternEvent(MainActivityC.java:191)
E/AndroidRuntime( 5940): 	at com.sunyata.kindmind.List.ListFragmentC.onOptionsItemSelected(ListFragmentC.java:436)
E/AndroidRuntime( 5940): 	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1568)
E/AndroidRuntime( 5940): 	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:1978)
E/AndroidRuntime( 5940): 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:367)
E/AndroidRuntime( 5940): 	at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:958)
E/AndroidRuntime( 5940): 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
E/AndroidRuntime( 5940): 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
E/AndroidRuntime( 5940): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
E/AndroidRuntime( 5940): 	at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:514)
E/AndroidRuntime( 5940): 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:99)
E/AndroidRuntime( 5940): 	at android.view.View.performClick(View.java:4084)
E/AndroidRuntime( 5940): 	at android.view.View$PerformClick.run(View.java:16966)
E/AndroidRuntime( 5940): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 5940): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 5940): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 5940): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 5940): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5940): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 5940): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 5940): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 5940): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by SunyataZero** [comment]
Hi, thank you very much for the feedback! You are the first person who has
made a change to the github page of this project that i have been working
on for so long. I am currently fully engaged in the Empathy App project
(also here on github and we are closing in on a release so may not be able
to get to this myself but if anyone else wants to take it i'll happily give
commit access)
Kind Regards,
Tord (SunyataZero)



On Thu, Feb 12, 2015 at 9:34 PM, Gennaro Imparato <notifications@github.com>
wrote:

> KindMind crashes on Click the first ActionBarMenuItem ("ic_action_accept")
> after change the orientation device.
>
> The StackTrace:
>
> E/AndroidRuntime( 5940): java.lang.NullPointerException
> E/AndroidRuntime( 5940): at
> android.content.ComponentName.(ComponentName.java:75)
> E/AndroidRuntime( 5940): at android.content.Intent.(Intent.java:3301)
> E/AndroidRuntime( 5940): at
> com.sunyata.kindmind.List.ListFragmentC.sortDataWithService(ListFragmentC.java:204)
> E/AndroidRuntime( 5940): at
> com.sunyata.kindmind.Main.MainActivityC.fireClearDatabaseAndUpdateGuiEvent(MainActivityC.java:234)
> E/AndroidRuntime( 5940): at
> com.sunyata.kindmind.Main.MainActivityC.fireSavePatternEvent(MainActivityC.java:191)
> E/AndroidRuntime( 5940): at
> com.sunyata.kindmind.List.ListFragmentC.onOptionsItemSelected(ListFragmentC.java:436)
> E/AndroidRuntime( 5940): at
> android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1568)
> E/AndroidRuntime( 5940): at
> android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:1978)
> E/AndroidRuntime( 5940): at
> android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:367)
> E/AndroidRuntime( 5940): at
> com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:958)
> E/AndroidRuntime( 5940): at
> com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
> E/AndroidRuntime( 5940): at
> com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
> E/AndroidRuntime( 5940): at
> com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
> E/AndroidRuntime( 5940): at
> com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:514)
> E/AndroidRuntime( 5940): at
> com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:99)
> E/AndroidRuntime( 5940): at android.view.View.performClick(View.java:4084)
> E/AndroidRuntime( 5940): at
> android.view.View$PerformClick.run(View.java:16966)
> E/AndroidRuntime( 5940): at
> android.os.Handler.handleCallback(Handler.java:615)
> E/AndroidRuntime( 5940): at
> android.os.Handler.dispatchMessage(Handler.java:92)
> E/AndroidRuntime( 5940): at android.os.Looper.loop(Looper.java:137)
> E/AndroidRuntime( 5940): at
> android.app.ActivityThread.main(ActivityThread.java:4745)
> E/AndroidRuntime( 5940): at java.lang.reflect.Method.invokeNative(Native
> Method)
> E/AndroidRuntime( 5940): at
> java.lang.reflect.Method.invoke(Method.java:511)
> E/AndroidRuntime( 5940): at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
> E/AndroidRuntime( 5940): at
> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
> E/AndroidRuntime( 5940): at dalvik.system.NativeStart.main(Native Method)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SunyataZero/KindMind/issues/4>.
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/
